application: remote-controller-api
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: remotecontroller.app

# Endpoints handler
- url: /_ah/api/.*
  script: sensors.APPLICATION
