application: sensors-api-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

# Endpoints handler
- url: /_ah/spi/.*
  script: sensors.APPLICATION

- url: /.*
  script: remotecontroller.app

libraries:
- name: pycrypto
  version: "2.6"

